// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgraSmp457vWwETAMUS_sa8YTPKF0_x5M',
    appId: '1:902859538080:web:c46d8b44093b1eb94953c5',
    messagingSenderId: '902859538080',
    projectId: 'chelsy-restaurant',
    authDomain: 'chelsy-restaurant.firebaseapp.com',
    storageBucket: 'chelsy-restaurant.firebasestorage.app',
    measurementId: 'G-J6FF8WN2HZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjt_FK_f5skNdJaGR46LPiRgzULIBOUFo',
    appId: '1:902859538080:android:02e578402b41bcab4953c5',
    messagingSenderId: '902859538080',
    projectId: 'chelsy-restaurant',
    storageBucket: 'chelsy-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyIlMt01VYDOf5wbcp8eheuQv-mdUDnns',
    appId: '1:902859538080:ios:2a244902e56b64b54953c5',
    messagingSenderId: '902859538080',
    projectId: 'chelsy-restaurant',
    storageBucket: 'chelsy-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.chelsyRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyIlMt01VYDOf5wbcp8eheuQv-mdUDnns',
    appId: '1:902859538080:ios:2a244902e56b64b54953c5',
    messagingSenderId: '902859538080',
    projectId: 'chelsy-restaurant',
    storageBucket: 'chelsy-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.chelsyRestaurant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgraSmp457vWwETAMUS_sa8YTPKF0_x5M',
    appId: '1:902859538080:web:7a0e8d3b02ac19874953c5',
    messagingSenderId: '902859538080',
    projectId: 'chelsy-restaurant',
    authDomain: 'chelsy-restaurant.firebaseapp.com',
    storageBucket: 'chelsy-restaurant.firebasestorage.app',
    measurementId: 'G-4KZX44RWRP',
  );
}
